### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by 1AGameMaster** [TTFH/Teardown-Converter#1]
Access Denied to C:\Users\<user>...

**Comment by 1AGameMaster** [comment]
Now, It cannot create info.txt files...

**Comment by 1AGameMaster** [comment]
This converter is a piece of shit...

**Comment by 1AGameMaster** [comment]
Error: Could not create info.txt
terminate called after throwing an instance of 'std::experimental::filesystem::v1::__cxx11::filesystem_error'
  what():  filesystem error: cannot create directories: Permission denied [C:\Users\User\Documents\Teardown\mods\lee_sandbox\main]

**Comment by TTFH** [comment]
You need to select the 3 paths on top to the right folders.
And you may also need to run as administrator

**Comment by 1AGameMaster** [comment]
How can I change defaults?
It always goes to its own locations

**Comment by 1AGameMaster** [comment]
where is config.xml?

**Comment by TTFH** [comment]
In the same folder that the executable

**Comment by 1AGameMaster** [comment]
![image](https://user-images.githubusercontent.com/73741427/174149482-fe26e0d1-049c-49b4-af9d-8ad2469fb8f4.png)

**Comment by 1AGameMaster** [comment]
you sure?

**Comment by TTFH** [comment]
That file is created after you open and close the converter.
But you can also edit the paths in the text inputs at the top: ![IMAGE](https://raw.githubusercontent.com/TTFH/Teardown-Converter/915781675c2beefefdfd99f4ebc837aaecb1db96/utils/converter_ui.png)

**Comment by 1AGameMaster** [comment]
there is no config.xml even after closing it...
