### ISSUE TITLE
this isnt really an issue but.... will this be updated to work with the time campers dlc? 

### ISSUE THREAD

**Issue by luca1808** [TTFH/Teardown-Converter#6]
i have checked and the time campers dlc even though in the mods catergory uses the TDBIN standard

**Comment by TTFH** [comment]
New version available:
https://github.com/TTFH/Teardown-Converter/releases/tag/v2.2

**Comment by luca1808** [comment]
quick question. is the update on the compiled version? i cannot compile it myself so i rely on the compiled one

**Comment by luca1808** [comment]
okay it is, but i have realised that um......... 
![image](https://github.com/TTFH/Teardown-Converter/assets/133994044/a7779fe2-d165-4e82-9af8-aa3e095cda9a)
that folder doesnt get created and causes issues same with the folders main/script only folder that does get created is script

**Comment by TTFH** [comment]
You may need to copy some folders manually, that probably won't get fixed.
