### ISSUE TITLE
Regarding OBJ / Model exporting?

### ISSUE THREAD

**Issue by MisterSirCode** [TTFH/Teardown-Converter#7]
In metarmask's old teardown converter, you could export scenes or quicksaves as OBJs so you could render them in blender.

Is something like that still possible?

Would love to be able to export destroyed scenes or finished maps as blender scenes to have finer control over renders and lighting (To have basically a better camera mode)

**Comment by TTFH** [comment]
You can use this program:
https://github.com/TTFH/Voxel-Render/releases/tag/blender

It may take a long time to convert to .obj and load into Blender for big maps.
